name: Wakatime Stats Update

on:
  schedule:
    # Runs every 4 hours
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Wakatime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anuraghazra/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # The following options are optional, but recommended
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: "true"
          SHOW_TOTAL_TIME: "true"
          SHOW_PROFILE_VIEWS: "false" # Set to false for a cleaner look
          COMMIT_MESSAGE: "Wakatime stats updated"
